---
web_root: /var/www/joomla

template_dir: "{{ project_root }}/templates"

site_domain: "{{ environment_domain }}"

site_aliases:
  - www.ofiarowanie.ddnsfree.com

public_url: https://"{{ environment_domain }}"

php_version: "8.4"
php_fpm_socket: "/run/php/php{{ php_version }}-fpm.sock"

# PHP tuning Joomla
php_memory_limit: "512M"
php_upload_max_filesize: "256M"
php_post_max_size: "256M"
php_max_execution_time: "300"
php_max_input_vars: "5000"

phpmyadmin_domain: "pma.{{ environment_domain }}"
phpmyadmin_root: /usr/share/phpmyadmin
phpmyadmin_db_name: phpmyadmin
phpmyadmin_db_user: pma
