---
- name: Configure NPM
  hosts: proxy
  become: true

  vars_files:
    - ../group_vars/all/vars.yml

  tasks:

    - name: Install Docker
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: true

    - name: Enable Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /opt/npm
        - /opt/npm/data
        - /opt/npm/letsencrypt

    - name: Deploy compose
      template:
        src: "{{ template_dir }}/npm-compose.yml.j2"
        dest: /opt/npm/docker-compose.yml

    - name: Create docker config directory
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        mode: "0755"

    - name: Configure Docker
      ansible.builtin.template:
        src: "{{ template_dir }}/daemon.json.j2"
        dest: /etc/docker/daemon.json
        mode: "0644"
      notify: restart docker

    - name: restart docker
      ansible.builtin.systemd:
        name: docker
        state: restarted

    - name: Start NPM
      community.docker.docker_compose_v2:
        project_src: /opt/npm